### ISSUE TITLE
plane-srgb scene renders black

### ISSUE THREAD

**Issue by wahn** [imallett/simple-spectral#4]
I don't know how the `plane-srgb` is supposed to render (I don't have access to the paper and don't see `Figure 1`), but for me the output is a black image. `cornell-srgb` renders fine though ...

**Comment by geometrian** [comment]
The preprint of our paper is freely available from my website, either from the project homepage or my research page in-general. Respectively:
https://graphics.geometrian.com/research/spectral-primaries.html
https://geometrian.com/research/index.php

---

The referenced problem was probably that there is an optimization for the "plane-srgb" scene where instead of using a Lambertian BRDF, it uses a mirror BRDF. This converges to exactly the same thing for this scene, but since the ray direction isn't a random variable, it converges a lot faster.

However, when explicit light sampling is enabled (as [it is](https://github.com/imallett/simple-spectral/blob/master/src/stdafx.hpp#L43) by default), it will actually converge infinitely slowly, since light sampling never hits a δ BRDF. You should have already gotten a warning about slower convergence being printed to the console/shell.

Yet, _infinitely_ slower convergence is probably unexpected, and not very user-friendly. In patch 6ac329d, I have made it so that this optimization is disabled when explicit light sampling is enabled. This should resolve the problem; thank you for reporting it.
